# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :release do
    match(type: "appstore", force_for_new_devices: false, readonly: true)
    increment_build_number
    gym(configuration: "Release", export_method: "app-store")
    deliver(skip_screenshots: true, skip_metadata: true, skip_app_version_update: true, precheck_include_in_app_purchases: false, api_key_path: "/Users/wenyou/Library/Mobile\ Documents/com~apple~CloudDocs/key/wenyoucn.json")
  end

  lane :add_device do
    device_name = prompt(text: "Enter the device name: ")
    device_udid = prompt(text: "Enter the device UDID: ")
    register_devices( devices: { device_name => device_udid } )
    match(type: "development", force_for_new_devices: true)
  end
end
